name: Build packages
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-flake-package:
    name: Build flake package
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build flake package
        run: nix build .#default
